### ISSUE TITLE
Missing dependecy on jaxb-runtime?

### ISSUE THREAD

**Issue by pkoziol** [arhs/sd-dss#10]
When I updated from DSS 4.3.0-RC to 4.3.0 I could not verify signatures because class com.sun.xml.bind.v2.model.annotation.AnnotationReader could not be found:

```
java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/annotation/AnnotationReader
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2521)
	at java.lang.Class.getMethod0(Class.java:2764)
	at java.lang.Class.getMethod(Class.java:1653)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:243)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:235)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:432)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:637)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at eu.europa.ec.markt.dss.validation102853.ValidationResourceManager.<clinit>(ValidationResourceManager.java:50)
	at eu.europa.ec.markt.dss.validation102853.SignedDocumentValidator.validateDocument(SignedDocumentValidator.java:365)
	at eu.europa.ec.markt.dss.validation102853.SignedDocumentValidator.validateDocument(SignedDocumentValidator.java:322)
	...
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.annotation.AnnotationReader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more

java.lang.NoClassDefFoundError: Could not initialize class eu.europa.ec.markt.dss.validation102853.ValidationResourceManager
	at eu.europa.ec.markt.dss.validation102853.SignedDocumentValidator.validateDocument(SignedDocumentValidator.java:365)
	at eu.europa.ec.markt.dss.validation102853.SignedDocumentValidator.validateDocument(SignedDocumentValidator.java:322)
	...
```

Adding dependency on jaxb-runtime solved the problem.
```xml
<dependency>
	<groupId>org.glassfish.jaxb</groupId>
	<artifactId>jaxb-runtime</artifactId>
	<version>2.2.10-b140310.1920</version>
</dependency>
```

**Comment by Bob88640** [comment]
in the main pom of 4.3.0 you can find:
```
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-impl</artifactId>
				<version>2.2.10-b140310.1920</version>
			</dependency>
```
and from version 4.3.1:
```
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-impl</artifactId>
				<version>2.2.11</version>
			</dependency>
```
I do not understand why did you have the problem...

**Comment by pkoziol** [comment]
I don't understand why I have to remember to look at main pom when I'm updating to newer DSS version and check if JAXB version has changed. Why don't define dependency on jaxb-runtime in main pom and everthing will update automatically?

Also, if I'm new DSS user, how do I know that I have to include this dependency myself? Is there any document with installation/dependency requirements?

**Comment by Bob88640** [comment]
I haven't got it right away, I'll do it

**Comment by Bob88640** [comment]
Please could you close the issue if you are satisfied with the proposed solution.
The origin of this issue comes from the change in jaxb impl:
the class: com.sun.xml.bind.v2.model.annotation.AnnotationReader moved from  jaxb-impl 2.2.6 to jaxb-core 2.2.7

**Comment by pkoziol** [comment]
Thanks.
